# Generated by Django 3.2.3 on 2021-07-07 19:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_auctionlisting_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='create_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 7, 7, 19, 39, 45, 808326, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='update_timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='pic',
            field=models.ImageField(upload_to='media'),
        ),
    ]
