# Generated by Django 3.2.3 on 2021-07-09 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auctionlisting_bids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionbid',
            name='current_price',
        ),
    ]
