# Generated by Django 3.2.3 on 2021-07-09 03:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_remove_auctionbid_current_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 16, 5, 12, 25, 806350)),
            preserve_default=False,
        ),
    ]
