# Generated by Django 3.2.3 on 2021-07-09 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auctionlisting_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionbid',
            name='bid_amount',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
