# Generated by Django 3.2.3 on 2021-07-10 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auctionbid_bid_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='bids',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bids', to='auctions.auctionbid'),
        ),
    ]
