# Generated by Django 3.2.3 on 2021-07-10 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auctioncomments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuctionComments',
            new_name='AuctionComment',
        ),
    ]
