# Generated by Django 3.2.3 on 2021-07-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_rename_auctioncomments_auctioncomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(choices=[('food', 'Food'), ('games', 'Games'), ('beauty', 'Beauty'), ('fitness', 'Fitness'), ('electronics', 'Electronics')], max_length=128)),
            ],
        ),
    ]
