# Generated by Django 3.2.3 on 2021-07-11 19:07

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categories',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('food', 'Food'), ('games', 'Games'), ('beauty', 'Beauty'), ('fitness', 'Fitness'), ('electronics', 'Electronics')], max_length=37),
        ),
    ]
