# Generated by Django 3.2.3 on 2021-07-11 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_alter_category_categories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='categories',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
