# Generated by Django 3.2.3 on 2021-07-12 02:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_auto_20210711_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='watchlist_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
