# Generated by Django 3.2.3 on 2021-07-17 01:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_auto_20210716_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='auction_winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='winner', to=settings.AUTH_USER_MODEL),
        ),
    ]
